### PR TITLE
vAlpha 1.3: Added UI (Under devleopment), currently doesn't work. New, more legible, version of the map.

### PR DESCRIPTION
**Pull request by hcps-ananda**
`/*
- Political Map Project
  *
- Name: Arvind Anand, Christian Womack, Tahir(Syed) Shezad
- Block:7
  *
- Program Purpose:
-  vAlpha 1.3: Added UI (Under devleopment), currently doesn't work. 
              New, more legible, version of the map.
  *
- Algorithm:
-  vAlpha 1.3: Same as v1.1
- Future/possible improvements: Make RBG Values. Need to scale the jFrame for any map drawn
  *`

### CODE REVIEW

**Comment by hcps-shehzadst** [comment]
@hcps-ananda Did you make your latest pull request, so that I can merge that with what I have on my computer

**Comment by hcps-ananda** [comment]
@hcps-shehzadst Yes I did, so we need to add our added functionality.

**Comment by hcps-shehzadst** [comment]
Yeah I need to think about what I want to add

**Comment by hcps-ananda** [comment]
From now on, can you comment on an opened issues if that's cool.

**Comment by hcps-shehzadst** [comment]
Yeah

**Pull request merged**
